### ISSUE TITLE
Are callbacks possible?

### ISSUE THREAD

**Issue by unbornchikken** [jiahansu/nodecl#1]
Hi,

I'm planning to make an OOP OpenCL wrapper library like what you can see in the official C++ bindings.

By using your stuff and https://www.npmjs.com/package/node-disposable , it could be achieved without puttin' in any more native code.

Just wanted to know is this possible to make OCL calls asynchronous? I mean can I create an event object, and call non blocking version of read memory API, that calls my JavaScript callback function definied on the event object?

Thanks for your answer.

**Comment by jiahansu** [comment]
Hi, unbornchikken

Sorry I am late in my reply

It is feasible to use event callback with nodecl library....because that nodecl uses BridJS (https://github.com/jiahansu/BridJS) to invoke native functions.  and the BridJS can help you to handle asynchronous callback whose thread is not even a V8's default thread...

You can find more info from BridJS  web page.

Best regards
